ui:
  ssl: true
  host: www.atlanticomedio.es
  port: 443
  nameSpace: /dspace

rest:
  ssl: true
  host: www.atlanticomedio.es
  port: 443
  nameSpace: /dspace/server

cache:
  msToLive: 900000
  control: max-age=60