services:
  dspacedb:
    image: dspace/dspace-postgres-pgcrypto:dspace-8.0
    container_name: dspacedb
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d:ro
    networks:
      - dspacenet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  dspace-solr:
    image: dspace/dspace-solr:dspace-8.0
    container_name: dspace-solr
    user: root
    volumes:
      - solr_data:/var/solr/data
    networks:
      - dspacenet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/admin/cores?action=STATUS"]
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint:
      - /bin/bash
      - '-c'
      - |
        init-var-solr

        precreate-core authority /opt/solr/server/solr/configsets/authority
        precreate-core oai /opt/solr/server/solr/configsets/oai
        precreate-core search /opt/solr/server/solr/configsets/search
        precreate-core statistics /opt/solr/server/solr/configsets/statistics

        exec solr-foreground -force

  dspace-backend:
    image: dspace/dspace:dspace-8.0
    container_name: dspace
    env_file:
      - .env.prod
    depends_on:
      dspacedb:
        condition: service_healthy
      dspace-solr:
        condition: service_healthy
    ports:
      - "8090:8080"
    environment:
      - JAVA_OPTS=-Xmx2048m -Xms1024m 
      - db__P__url=jdbc:postgresql://dspacedb:5432/${DB_NAME} 
      - db__P__username=${DB_USER} 
      - db__P__password=${DB_PASSWORD} 
      - solr__P__server=http://dspace-solr:8983/solr 
      - dspace__P__server__P__url=https://192.168.0.236/dspace/server
      - dspace__P__ui__P__url=https://192.168.0.236/dspace
      - dspace__P__dir=/dspace
      - rest__cors__allowed-origins=https://192.168.0.236
    volumes:
      - assetstore:/dspace/assetstore
    networks:
      - dspacenet
    entrypoint: 
      - /bin/bash
      - -c
      - |
        while (! </dev/tcp/dspacedb/5432) > /dev/null 2>&1; do sleep 1; done;
        sleep 3;
        /dspace/bin/dspace database repair
        /dspace/bin/dspace database migrate
        mkdir -p /dspace/log && ln -sf /dev/stdout /dspace/log/dspace.log
        exec java $$JAVA_OPTS -jar /dspace/webapps/server-boot.jar --dspace.dir=/dspace --server.servlet.context-path=/dspace/server --server.forward-headers-strategy=FRAMEWORK


  dspace-angular:
    # image: dspace/dspace-angular:dspace-8.0
    container_name: dspace-angular
    build:
      context: ./dspace-angular
      dockerfile: Dockerfile.dist
    env_file:
      - .env.prod
    depends_on:
      - dspace-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - DSPACE_HOST=0.0.0.0
      - DSPACE_PORT=4000
      - DSPACE_NAMESPACE=/dspace
      - DSPACE_SSL=false

      - DSPACE_REST_HOST=192.168.0.236
      - DSPACE_REST_PORT=443
      - DSPACE_REST_NAMESPACE=/dspace/server
      - DSPACE_REST_SSL=true

      # Reduce bot cache TTL from 1 day to 5 minutes to avoid caching error pages for too long
      - DSPACE_CACHE_SERVERSIDE_BOTCACHE_TIMETOLIVE=300000
    extra_hosts:
      - "192.168.0.236:host-gateway"
    networks:
      - dspacenet

networks:
  dspacenet:

volumes:
  pgdata:
  solr_data:
  assetstore: