FROM registry.cern.ch/inveniosoftware/almalinux:1

RUN dnf -y install python3.12 python3.12-devel python3.12-libs python3.12-pip && \
    alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1 && \
    alternatives --set python3 /usr/bin/python3.12 && \
    python3.12 -m pip install --upgrade pip && \
    python3.12 -m pip install pipenv

COPY site ./site
COPY Pipfile Pipfile.lock ./
RUN pipenv install --deploy --system

COPY ./docker/uwsgi/ ${INVENIO_INSTANCE_PATH}
COPY ./invenio.cfg ${INVENIO_INSTANCE_PATH}
COPY ./templates/ ${INVENIO_INSTANCE_PATH}/templates/
COPY ./app_data/ ${INVENIO_INSTANCE_PATH}/app_data/
COPY ./translations/ ${INVENIO_INSTANCE_PATH}/translations/
COPY ./ .

RUN mkdir -p ${INVENIO_INSTANCE_PATH}/assets/ && \
    cp -r ./static/. ${INVENIO_INSTANCE_PATH}/static/ && \
    cp -r ./assets/. ${INVENIO_INSTANCE_PATH}/assets/ && \
    invenio collect --verbose && \
    invenio webpack buildall

ENV INVENIO_SITE_UI_URL=http://localhost:5000
ENV INVENIO_SITE_API_URL=http://localhost:5000/api
ENV FLASK_ENV=development

EXPOSE 5000

CMD ["invenio", "run", "--host", "0.0.0.0", "--port", "5000"]
